"""Reporter — assembles accepted findings into a narrative Markdown report."""

from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path

from .models import Finding


def generate_report(
    case_id: str,
    accepted: list[Finding],
    unverified: list[Finding],
    session_dir: Path,
    log_hash: str,
) -> Path:
    """Generate a Markdown investigation report."""
    report_path = session_dir / "report.md"
    report_json_path = session_dir / "report.json"

    lines = []
    lines.append(f"# SIFT Sentinel Investigation Report")
    lines.append(f"")
    lines.append(f"**Case ID:** {case_id}")
    lines.append(f"**Generated:** {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M:%S UTC')}")
    lines.append(f"**Execution log hash:** `{log_hash}`")
    lines.append(f"**Findings accepted:** {len(accepted)}")
    lines.append(f"**Findings unverified:** {len(unverified)}")
    lines.append(f"")
    lines.append(f"---")
    lines.append(f"")

    # Executive summary
    lines.append(f"## Executive Summary")
    lines.append(f"")
    if accepted:
        sev_counts = {}
        for f in accepted:
            sev_counts[f.severity] = sev_counts.get(f.severity, 0) + 1
        sev_str = ", ".join(f"{v} {k}" for k, v in sorted(sev_counts.items()))
        lines.append(f"This investigation produced {len(accepted)} verified finding(s) ({sev_str}).")
        mitre = set()
        for f in accepted:
            mitre.update(f.mitre_attack)
        if mitre:
            lines.append(f"MITRE ATT&CK techniques observed: {', '.join(sorted(mitre))}.")
    else:
        lines.append(f"No findings were accepted by the Skeptic review process.")
    lines.append(f"")

    # Accepted findings
    if accepted:
        lines.append(f"## Verified Findings")
        lines.append(f"")
        for i, finding in enumerate(accepted, 1):
            lines.append(f"### Finding {i}: {finding.title}")
            lines.append(f"")
            lines.append(f"**Severity:** {finding.severity} | "
                        f"**Type:** {finding.claim_type} | "
                        f"**Skeptic iterations:** {finding.iteration + 1}")
            if finding.mitre_attack:
                lines.append(f"**MITRE ATT&CK:** {', '.join(finding.mitre_attack)}")
            lines.append(f"")
            lines.append(finding.narrative)
            lines.append(f"")

            # Citations
            lines.append(f"**Evidence Citations:**")
            lines.append(f"")
            for j, cit in enumerate(finding.evidence, 1):
                lines.append(f"  [{j}] `{cit.locator_type}`: `{cit.locator}` "
                           f"in `{cit.artifact}`")
                if cit.excerpt:
                    lines.append(f"      Excerpt: {cit.excerpt[:120]}")
            lines.append(f"")

            # Timeline
            if finding.timeline:
                lines.append(f"**Timeline:**")
                lines.append(f"")
                for te in finding.timeline:
                    lines.append(f"  - {te.timestamp_utc.strftime('%Y-%m-%d %H:%M:%S')} "
                               f"({te.source}): {te.description} [citation {te.citation_index + 1}]")
                lines.append(f"")

            lines.append(f"---")
            lines.append(f"")

    # Unverified hypotheses
    if unverified:
        lines.append(f"## Unverified Hypotheses")
        lines.append(f"")
        lines.append(f"The following findings were not accepted after maximum Skeptic iterations. "
                    f"They are included for transparency and further manual review.")
        lines.append(f"")
        for i, finding in enumerate(unverified, 1):
            lines.append(f"### Hypothesis {i}: {finding.title}")
            lines.append(f"")
            lines.append(f"**Severity:** {finding.severity} | **Final verdict:** {finding.skeptic_verdict}")
            lines.append(f"")
            lines.append(finding.narrative)
            lines.append(f"")
            lines.append(f"---")
            lines.append(f"")

    # Audit trail
    lines.append(f"## Audit Trail")
    lines.append(f"")
    lines.append(f"This report was generated by SIFT Sentinel's dual-agent architecture. "
                f"Every finding above was independently verified by the Skeptic agent, "
                f"which re-executed citation lookups to confirm the evidence exists at "
                f"the claimed locations.")
    lines.append(f"")
    lines.append(f"- Execution log: `{session_dir}/execution.jsonl`")
    lines.append(f"- Iteration traces: `{session_dir.parent}/iterations/`")
    lines.append(f"- Execution log SHA-256: `{log_hash}`")
    lines.append(f"")
    lines.append(f"To verify any citation, re-run the corresponding tool call from the execution log "
                f"and confirm the output matches.")

    report_text = "\n".join(lines)

    # Write markdown
    with open(report_path, "w") as f:
        f.write(report_text)

    # Write structured JSON
    report_data = {
        "case_id": case_id,
        "generated_utc": datetime.now(timezone.utc).isoformat(),
        "log_hash": log_hash,
        "accepted_findings": [f.model_dump(mode="json") for f in accepted],
        "unverified_hypotheses": [f.model_dump(mode="json") for f in unverified],
    }
    with open(report_json_path, "w") as f:
        json.dump(report_data, f, indent=2, default=str)

    return report_path
